### ISSUE TITLE
Edit or Add spins

### ISSUE THREAD

**Issue by tomsherrod** [MonsantoCo/cf-users#8]
Hi,

I'm giving cf-users a try. "User Role Admin" appears to work fine.
If "Edit User" or "Add User", page appears to spin and then stops without producing any information. (CF is using ldap/AD for login)

Pointers on how to debug what the problem are appreciated.

Thanks,
Tom

**Comment by mjseid** [comment]
So User Role Admin page works, does it allow you to add/remove permissions to users based on you access?

For the Edit and Add pages, when you say they spin without producing any information do they fully render and give you an Organization bar with a drop-down like in the ReadMe pics?  

Any errors if you inspect the page with chrome dev-tools?

**Comment by tomsherrod** [comment]
The User Role Admin page does allow add/remove with no problem.

The Edit and Add pages, spin and then render. The dropdowns are there with no match found.

Chrome dev-tool does give a 502 Bad Gateway from this query:
https://cf-users.run.domain.com/cf-users/cf-api/users/94317f07-4bb5-43c4-bb57-b03493d3d8a9/organizations
(good pointer, thanks.)

The cf-users app was deployed in the "system" domain, *.run.domain.com. Should it be put in the "apps" domain?
Where to look for the setting creating the bad gateway?

Thanks again.

**Comment by mjseid** [comment]
If you check logs when you deploy the app, are you seeing anything about an Access Token Error or Bad credentials?

The role admin tab uses the UAA client creds and the other tabs use the portal admin creds, so it seems like your portal admin creds might be bad.  Can you verify the portal-id are the base64 encoded strings of "admin" and it's password?

**Comment by tomsherrod** [comment]
Redeployed the app, watching the logs, no errors.

cf env cf-users showed the "credentials". The portal-id and password are base64 versions of the same admin account use for a "cf login" of admin. Is there another one?

Any other logs to review?

**Comment by tomsherrod** [comment]
I tried running "npm run dev" after modifying the gulpfile.coffee with the environment information.
See this in the output:
Access Token Error {
  "error": "unauthorized",
  "error_description": "Bad credentials"
}

I've tested the credentials multiple times with uaac and cf login. Verified the base64.
I'm stumped. 
Another way to see what's going on?

Tom

**Comment by mjseid** [comment]
The portal id/password are the same one's you'd use to login via
cf login -a https://api.blah.domain.com -u admin -p supersecretpassword

The issue you're describing (token error in the log and spinner with not output on the edit and add tabs) is what we see when we have bad passwords for the portal user.

You might be able to verify by connecting to the uaa(s) and looking at the logs under /var/vcap/sys/log/uaa/uaa_events.log for AuthenticationFailure of admin

**Comment by tomsherrod** [comment]
Now that's the odd part.
While tailing uaa_events.log, log in to cf-users, select "Edit User", nothing comes from the log while the browser spins.
Once the spinning stops, 2 entries come into the uaa_events.log:
[2016-10-20 12:05:43.117] uaa - 6072 [http-nio-8080-exec-8] ....  INFO --- Audit: ClientAuthenticationSuccess ('Client authentication success'): principal=cf, origin=[remoteAddress=10.104.63.226, clientId=cf], identityZoneId=[uaa]

[2016-10-20 12:05:43.155] uaa - 6072 [http-nio-8080-exec-8] ....  INFO --- Audit: TokenIssuedEvent ('["cloud_controller.read","password.write","cloud_controller.write","openid","doppler.firehose","scim.write","scim.read","cloud_controller.admin","uaa.user"]'): principal=94317f07-4bb5-43c4-bb57-b03493d3d8a9, origin=[caller=cf, details=(remoteAddress=10.104.63.226, clientId=cf)], identityZoneId=[uaa]

One of the logins (portal login?) isn't even getting to uaa?

**Comment by tomsherrod** [comment]
Examining the haproxy log:
Click Edit User:
Oct 20 14:41:47 localhost haproxy[10320]: 10.17.9.37:50390 [20/Oct/2016:14:41:47.491] https-in~ http-routers/node0 2/0/0/3/5 200 743 - - ---- 12/12/3/4/0 0/0 "GET /cf-users/roles HTTP/1.1"

Spinning stops:
Oct 20 14:43:47 localhost haproxy[10320]: 10.17.9.37:50389 [20/Oct/2016:14:41:33.890] https-in~ http-routers/node0 13595/0/0/120004/133599 502 319 - - ---- 11/11/1/2/0 0/0 "GET /cf-users/cf-api/users/94317f07-4bb5-43c4-bb57-b03493d3d8a9/organizations HTTP/1.1"

Wonder if the list of users from ldap/AD is causing a timeout.

**Comment by DerekTandy** [comment]
Hey @tomsherrod, I've just pushed an update to log out more information in the AdminOauth file.  I've also set it to allow you to turn on way too many logs by setting the environment variable `NODE_DEBUG=OAUTH`.  That will print the error and response from every attempt to fetch and refresh the token, plus the user, password and client it is attempting to use.  (I wouldn't set that variable live, just locally).  We've also added some basic oauth user scope verification to check what we can to ensure the client id is set up properly.  

If you don't mind pull the latest master, run `npm install; NODE_DEBUG=OAUTH npm run dev`

The cf-users application never actually calls AD, it goes directly to UAA, so we're curious how many orgs/spaces/users your Cloud Foundry environment has.  Our heaviest install has (15 orgs, 43 spaces and 400 users).

**Comment by tomsherrod** [comment]
Well, this is embarrassing. 
@mjseid, was right from the beginning. @DerekTandy, proved him correct.
The debug printed out the ids and passwords, 'correctid\n' and 'correctpassword\n'  Note the new line character.
Once the encoder and I agreed on the credentials, without the new line character, it all worked. The part I was looking for, adding new users that allowed AD users to log in and be assigned org/role. YES, it works.
This is a v244 new runtime with 2 orgs and 2 users. We'll see how big it gets!

Thank you!
