### ISSUE TITLE
Issues deploying on CFv250 release

### ISSUE THREAD

**Issue by jocono** [MonsantoCo/cf-users#9]
We have been successfully deploying and using cf-users with our cloud foundry v240 environments.  When we upgraded our test environment to v250, we are now unable to successfully run cf-users.  The application deploys but gives a Status: Error Internal Server Error (500 error) in the browser after successful login and when attempting to redirect to /cf-users/roles/   We have looked at cf logs cf-users and it does not log any errors.  Any suggestions?

**Comment by DerekTandy** [comment]
We are currently running cf-users successfully against Cloud Foundry v252.  We did skip version v250, but really doubt that it’s a version issue if v252 works.  

There’s not a lot to go on here.  If I were you, I’d double check the service binding, look to see if there is any more information in your browser’s console log or networking log.  I’d then try to run the app locally and to add logging statements.
